# Generated by Django 5.1.15 on 2026-06-21 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('assistant_type', models.CharField(choices=[('PRODUCT_SEARCH', 'AI Medicine Search Assistant'), ('HEALTH_INFO', 'AI Health Information Assistant'), ('RECOMMENDATION', 'AI Product Recommendation Engine')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('referenced_products', models.JSONField(blank=True, default=list)),
                ('disclaimer_shown', models.BooleanField(default=False, help_text='Whether the mandatory medical disclaimer was attached to this message')),
                ('groq_model', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
