# Generated by Django 5.1.15 on 2026-06-21 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(help_text='Cloudinary/S3 secure URL')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('PDF', 'PDF')], max_length=10)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('patient_name', models.CharField(blank=True, help_text='Name on prescription, may differ from account holder', max_length=255)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('doctor_license_number', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('access_token', models.CharField(blank=True, help_text='Time-limited token for secure pharmacist viewing link', max_length=64)),
                ('valid_until', models.DateField(blank=True, help_text='Prescription validity expiry per regulatory requirement', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('instructions', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CLARIFICATION', 'Needs Clarification')], max_length=25)),
                ('comments', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
