# Generated by Django 5.1.15 on 2026-06-21 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='assigned_pharmacist',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PHARMACIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='prescriptionreview',
            name='pharmacist',
            field=models.ForeignKey(limit_choices_to={'role': 'PHARMACIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionreview',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='prescriptions.prescription'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['user', 'status'], name='prescriptio_user_id_8d7193_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', '-created_at'], name='prescriptio_status_565a46_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['assigned_pharmacist', 'status'], name='prescriptio_assigne_54d334_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionreview',
            index=models.Index(fields=['prescription', '-created_at'], name='prescriptio_prescri_77223a_idx'),
        ),
    ]
