# Generated by Django 5.1.15 on 2026-07-04 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Manufacturer that owns or markets this brand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='products.manufacturer'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='products_br_name_0925fd_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='products_br_slug_d4d839_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['manufacturer'], name='products_br_manufac_301c61_idx'),
        ),
    ]
