# Generated by Django 5.1.15 on 2026-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_manufacturer_brand_products_br_name_0925fd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
