# Generated by Django 5.1.15 on 2026-07-14 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_manufacturer_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('SAME_GENERIC', 'Same Generic'), ('SAME_CATEGORY', 'Same Category'), ('BOUGHT_TOGETHER', 'Bought Together')], max_length=30)),
                ('score', models.PositiveSmallIntegerField(default=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='products.product')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='products_pr_product_9ea154_idx'), models.Index(fields=['related_product'], name='products_pr_related_cbd7c7_idx'), models.Index(fields=['relation_type'], name='products_pr_relatio_0c8d0b_idx')],
                'unique_together': {('product', 'related_product', 'relation_type')},
            },
        ),
    ]
