# Generated by Django 5.1.15 on 2026-07-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_size',
            field=models.CharField(blank=True, default='', help_text="e.g. 'Strip of 10', 'Bottle of 100ml', 'Box of 30 Capsules'", max_length=100),
        ),
    ]
