# Generated by Django 5.1.15 on 2026-07-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_package_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_pack_quantity',
            field=models.PositiveIntegerField(blank=True, help_text="Total tablets/capsules/units in the manufacturer's original pack (e.g. 1000 for a box containing 100 strips of 10)", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_unit_type',
            field=models.CharField(blank=True, choices=[('STRIP', 'Strip'), ('FULL_PACK', 'Full Pack')], help_text='Auto-computed: packs of 100+ units sell per strip; under 100 sell as full pack.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_strip',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Tablets/capsules per strip, if the product is strip-packaged (e.g. 10)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
